//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul4
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class PackPO
    {
        public int IDPackPO { get; set; }
        public Nullable<int> PackID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; } = .00M;



        public void add(int PackID, Product product)
        {
            this.PackID = PackID;
            this.ProductID = product.IDProduct;
            this.Amount = product.Amount;
            this.Price = product.Price;
            using (var context = new projektkinoEntities1())
            {
                context.PackPO.Add(this);
                context.SaveChanges();
            }
        }
    }
}
