//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul4
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class Product
    {
        public int IDProduct { get; set; }
        public decimal Price { get; set; } = .00M;
        public string Name { get; set; }
        public int Amount { get; set; }

        public static void add(string name, decimal price, int amount)
        {
            Product product = new Product();
            product.Name = name;
            product.Price = price;
            product.Amount = amount;
            using (var context = new projektkinoEntities1())
            {
                context.Product.Add(product);
                context.SaveChanges();
            }

        }

        public static void edit(int index, string name, decimal price, int amount)
        {
            using (var context = new projektkinoEntities1())
            {
                Product product = context.Product.Find(index);
                product.Name = name;
                product.Price = price;
                product.Amount = amount;
                context.SaveChanges();
            }
        }

        public static void Delete(int index)
        {
            using (var context = new projektkinoEntities1())
            {
                Product product = context.Product.Find(index);
                context.Entry(product).State = System.Data.Entity.EntityState.Deleted;
                context.SaveChanges();
            }
        }

        public override string ToString()
        {
            return Name + " --- " + Price + " PLN";
        }
    }
}
