//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul4
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class SalePO
    {
        public int IDSalePO { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> PackID { get; set; }
        public decimal Price { get; set; } = .00M;

        public void add(int SaleID, Pack pack)
        {
            this.SaleID = SaleID;
            this.PackID = pack.IDPack;
            this.Price = pack.Price;
            using (var context = new projektkinoEntities1())
            {
                context.SalePO.Add(this);
                context.SaveChanges();
            }
        }
    }
}
