//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IDSale { get; set; }
        public int UserID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public decimal Price { get; set; } = .00M;

        public int add(int UserID, DateTime date, decimal Price)
        {
            this.UserID = UserID;
            this.SaleDate = date;
            this.Price = Price;
            using (var context = new projektkinoEntities1())
            {
                context.Sale.Add(this);
                context.SaveChanges();
                return this.IDSale;
            }
        }
    }
}
