//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class g1_code
    {
        public int id_code { get; set; }
        public int id_user { get; set; }
        public string code { get; set; }
        public System.DateTime code_date { get; set; }
    }
}
