//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class g1_permission_list
    {
        public int id_permission_list { get; set; }
        public int id_user { get; set; }
        public int id_permission { get; set; }
    
        public virtual g1_permission g1_permission { get; set; }
        public virtual g1_permission_list g1_permission_list1 { get; set; }
        public virtual g1_permission_list g1_permission_list2 { get; set; }
        public virtual g1_user g1_user { get; set; }
    }
}
