//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class g1_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public g1_user()
        {
            this.g1_permission_list = new HashSet<g1_permission_list>();
            this.Schedules = new HashSet<Schedule>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int id_user { get; set; }
        public Nullable<int> id_pearson { get; set; }
        public Nullable<int> id_position { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string e_mail { get; set; }
    
        public virtual g1_pearson g1_pearson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<g1_permission_list> g1_permission_list { get; set; }
        public virtual g1_position g1_position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
