//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviePerson
    {
        public int id { get; set; }
        public int movie { get; set; }
        public int person { get; set; }
        public int personType { get; set; }
    
        public virtual Movie Movie1 { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual PersonType PersonType1 { get; set; }
    }
}
