//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performance()
        {
            this.Timetables = new HashSet<Timetable>();
        }
    
        public int id { get; set; }
        public int movie { get; set; }
        public int hall { get; set; }
        public System.TimeSpan adsDuration { get; set; }
    
        public virtual Hall Hall1 { get; set; }
        public virtual Movie Movie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timetable> Timetables { get; set; }

        public override string ToString()
        {
            return Movie1.title + "  " + Hall1.name;
        }

    }
}
