//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public string type { get; set; }
        public decimal price { get; set; }
        public int id_Reservation { get; set; }
        public int id_Seat { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
