//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int id { get; set; }
        public int performance { get; set; }
        public System.DateTime performanceDate { get; set; }
    
        public virtual Performance Performance1 { get; set; }

    }
}
