//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimsMovie
    {
        public int id { get; set; }
        public int movie { get; set; }
        public int dim { get; set; }
    
        public virtual Dim Dim1 { get; set; }
        public virtual Movie Movie1 { get; set; }
    }
}
